services:
  - type: web
    name: hoffee-shop-app
    env: python
    buildCommand: "./render_build.sh"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    autoDeploy: false
